name: web_pulse_edu
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  webview_flutter: ^4.0.1
  url_launcher: ^6.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_launcher_icons: "^0.9.2"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon.png"  

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
